"""
Database Schema Setup for Meshtastic Node Management
Run this once to create the required tables and indexes
"""

CREATE_MESH_NODES_TABLE = """
CREATE TABLE MESH_NODES (
    NODE_ID VARCHAR2(50) PRIMARY KEY,
    SHORT_NAME VARCHAR2(20),
    LONG_NAME VARCHAR2(100),
    AKA VARCHAR2(50),
    HARDWARE VARCHAR2(50),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    ALTITUDE NUMBER(10,2),
    HOPS_AWAY NUMBER(3),
    CHANNEL VARCHAR2(20),
    FIRST_HEARD TIMESTAMP NOT NULL,
    LAST_HEARD TIMESTAMP NOT NULL,
    TIMES_HEARD CLOB,  -- JSON array of all timestamps
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1))
)
"""

CREATE_INDEXES = [
    "CREATE INDEX IDX_MESH_NODES_LAST_HEARD ON MESH_NODES(LAST_HEARD)",
    "CREATE INDEX IDX_MESH_NODES_FIRST_HEARD ON MESH_NODES(FIRST_HEARD)",
    "CREATE INDEX IDX_MESH_NODES_ACTIVE ON MESH_NODES(IS_ACTIVE)",
    "CREATE INDEX IDX_MESH_NODES_CHANNEL ON MESH_NODES(CHANNEL)"
]

CREATE_UPDATE_TRIGGER = """
CREATE OR REPLACE TRIGGER TRG_MESH_NODES_UPDATE
    BEFORE UPDATE ON MESH_NODES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
"""

# Future logging table (Step 2)
CREATE_PROCESS_LOG_TABLE = """
CREATE TABLE MESH_PROCESS_LOG (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROCESS_NAME VARCHAR2(50) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('RUNNING', 'SUCCESS', 'ERROR')),
    RECORDS_ADDED NUMBER DEFAULT 0,
    RECORDS_UPDATED NUMBER DEFAULT 0,
    RECORDS_MARKED_INACTIVE NUMBER DEFAULT 0,
    ERROR_MESSAGE CLOB,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

def setup_database_schema():
    """
    Set up the complete database schema.
    Run this once during initial setup.
    """
    from oracle_db_manager import get_db_manager
    
    db = get_db_manager()
    
    try:
        # Create main table
        print("Creating MESH_NODES table...")
        db.execute_dml(CREATE_MESH_NODES_TABLE)
        
        # Create indexes
        print("Creating indexes...")
        for index_sql in CREATE_INDEXES:
            db.execute_dml(index_sql)
        
        # Create trigger
        print("Creating update trigger...")
        db.execute_dml(CREATE_UPDATE_TRIGGER)
        
        print("Database schema setup completed successfully!")
        
    except Exception as e:
        print(f"Error setting up database schema: {e}")
        raise

if __name__ == "__main__":
    setup_database_schema()